version: '3'

services:
  api-server:
    build:
      context: .
    container_name: trello-clone-api
    image: trello-clone-api
    restart: unless-stopped
    env_file:
      - .env

    networks:
      - app-network

    ports:
      - '3001:3333'

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: nginx-server
    restart: unless-stopped

    networks:
      - app-network

    ports:
      - '80:3001'

    depends_on:
      - api-server

networks:
  app-network:
    driver: bridge
